vich_uploader:
    db_driver: orm

    mappings:
         utilisateur_images:
             uri_prefix: '%uploads_path%'
             upload_destination: '%kernel.project_dir%/public/%uploads_path%'
         utlisateur_pdf:
             uri_prefix: '%uploads_path%'
             upload_destination: '%kernel.project_dir%/public/PDF'